version: "3.9"
services:
  backend:
    image: mernlib-backend
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  front:
    image: mernlib-frontend
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: