version: "3.9"
services:
  
  backend:
    build: ./backend
    ports:
      #Map/Port forward from Host -> Container
      - "4000:4000"
    container_name: mernlibraryback-container-prod
    #image: public.ecr.aws/y9k8p9q8/mernlibrary-backend:2.5
    #image: 548172022186.dkr.ecr.us-east-1.amazonaws.com/mernlib-back-use1:3.44
#    networks:
#      - mern-network
  
#   front:
#     build: ./front
#     ports:
#       - "3000:3000"
#     container_name: mernlibraryfront-container
#     image: public.ecr.aws/y9k8p9q8/mernlibrary-frontend:2.0
# #    networks:
# #      - mern-network
#     stdin_open: true
#     tty: true
#     depends_on:
#       - backend

#networks:
#  mern-network:
#    driver: bridge 